logging:
  level:
    org.springframework: ERROR
    com.ibm: DEBUG

spring:
  profiles:
    active: dev

plivoProperty:
  authId: swara
  authtoken: swara

xlsFilesProperty:
  empContactPath : /swara/
  accountClaimsPath : /swara/